"/": 
  - 
    GET: "posts#index"

"/posts/new":
  -
    GET: "posts#new"

/posts: 
  - 
    GET: "posts#index"
  - 
    POST: "posts#create"

"/posts/:id": 
  - 
    GET: "posts#show"
  -
    DELETE: "posts#delete"
  -
    PATCH: "posts#update"

"/posts/edit":
  - GET: "posts#edit"